
--- Processing started at 2025-03-21 17:17:06 ---
[2025-03-21 17:17:08] Error processing ./0x8e903856407d1c0cc90fa273130f3605ece6cd01.png: cannot identify image file './0x8e903856407d1c0cc90fa273130f3605ece6cd01.png'
Traceback (most recent call last):
  File "/home/groninge/projects/tokenlists/src/assets/images/tokens/tt.py", line 37, in process_image
    img = Image.open(image_path)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/groninge/.pyenv/versions/3.12.1/lib/python3.12/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file './0x8e903856407d1c0cc90fa273130f3605ece6cd01.png'

[2025-03-21 17:17:09] Error processing ./0x64b76158c3a9176b0ef6c00d1b957f10c07663d8.png: cannot identify image file './0x64b76158c3a9176b0ef6c00d1b957f10c07663d8.png'
Traceback (most recent call last):
  File "/home/groninge/projects/tokenlists/src/assets/images/tokens/tt.py", line 37, in process_image
    img = Image.open(image_path)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/groninge/.pyenv/versions/3.12.1/lib/python3.12/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file './0x64b76158c3a9176b0ef6c00d1b957f10c07663d8.png'

[2025-03-21 17:17:12] Error processing ./0x6340ce0f2b9271b59ab89d1320fbe1a51b6fdde7.png: cannot identify image file './0x6340ce0f2b9271b59ab89d1320fbe1a51b6fdde7.png'
Traceback (most recent call last):
  File "/home/groninge/projects/tokenlists/src/assets/images/tokens/tt.py", line 37, in process_image
    img = Image.open(image_path)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/groninge/.pyenv/versions/3.12.1/lib/python3.12/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file './0x6340ce0f2b9271b59ab89d1320fbe1a51b6fdde7.png'

Processed 9 out of 834 PNG images.
--- Processing completed at 2025-03-21 17:17:13 ---
